version: '3.7'

services:

  wfs3:
    build: .
    image: flaviostutz/wfs3
    ports: 
      - 8080:8080
    restart: always
    environment:
      - POSTGRES_HOST=postgis
      - POSTGRES_USERNAME=wfs3
      - POSTGRES_PASSWORD=wfs3
      - POSTGRES_DBNAME=wfs3

  pgweb:
    image: sosedoff/pgweb:0.11.2
    ports:
      - 8081:8081
    restart: always
    environment:
      - DATABASE_URL=postgres://wfs3:wfs3@postgis:5432/wfs3?sslmode=disable

  # pgadmin:
  #   image: dpage/pgadmin4:4.8
  #   ports:
  #     - 8081:80
  #   restart: always
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=admin
  #     - PGADMIN_DEFAULT_PASSWORD=admin

  postgis:
    # image: timescale/timescaledb-postgis:1.3.1-pg9.6
    image: mdillon/postgis:11-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=wfs3
      - POSTGRES_PASSWORD=wfs3
      - POSTGRES_DB=wfs3
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:

