version: '3.7'

services:

  wfs3:
    build: .
    image: flaviostutz/wfs3
    ports: 
      - 8080:8080
    restart: always
    environment:
      - POSTGRES_HOST=postgis
      - POSTGRES_USERNAME=wfs3
      - POSTGRES_PASSWORD=wfs3
      - POSTGRES_DBNAME=wfs3

  web:
    image: sosedoff/pgweb:0.11.2
    ports:
      - 8081:8081
    restart: always
    environment:
      - DATABASE_URL=postgres://wfs3:wfs3@postgis:5432/wfs3?sslmode=disable

  postgis:
    image: timescale/timescaledb-postgis:1.3.0-pg11
    # image: mdillon/postgis:9.6-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=wfs3
      - POSTGRES_PASSWORD=wfs3
      - POSTGRES_DB=wfs3
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:

