version: '3.7'

volumes:
  pg-data:
    driver: local

services:
  wfs3:
    image: boundlessgeo/wfs3
    restart: always
    build: .
    links:
      - db
    depends_on:
      - db
    ports: 
      - 8080:8080
    environment:
      - POSTGRES_HOST=db

  db:
    container_name: db
    build: ./docker/postgis
    image: wfsthree/postgis:latest
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  web:
    container_name: web  # optional
    restart: always  # optional
    image: sosedoff/pgweb
    ports:
      - "8081:8081"
    links:
      - db:db
    environment:
      - DATABASE_URL=postgres://wfsthree:wfsthree@db:5432/wfsthree?sslmode=disable
    depends_on:
      - db
